### ISSUE TITLE
Unterschied SOAP / REST

### ISSUE THREAD

**Issue by QuadStingray** [OpenLigaDB/OpenLigaDB-Samples#12]
Hallo Zusammen, 

ist in der neuen API alles aus der SOAP API umgesetzt, oder nur die in der README.md beschriebenen? 
Besonders interessant ist für mich die Methode GetMatchdataByTeams. Ich habe einfach mal versucht mir die Route zusammenzubauen, leider ohne Erfolg! https://www.openligadb.de/api/getmatchdatabyteams/40/7

40 sollte meiner Meinung nach FCB und 7 BVB sein!

Viele Grüße

**Comment by msiggi** [comment]
Hi,

ja, es sind noch nicht alle SOAP-Methoden in der JSON-Api konsequent umgesetzt. Danke für den Hinweis, die Realisierung läuft.

**Comment by msiggi** [comment]
Hi,
so, ist drin: Bayern gegen München: https://www.openligadb.de/api/getmatchdata/40/7
