### ISSUE TITLE
Zugriff auf Saison

### ISSUE THREAD

**Issue by nilskoppelmann** [OpenLigaDB/OpenLigaDB-Samples#15]
Wie kann ich die aktuelle Saison einer Liga auslesen?
Soweit ich das sehe besteht diese Möglichkeit aktuell nicht oder?

**Comment by msiggi** [comment]
So z.B., dass [hier](https://www.openligadb.de/api/getcurrentgroup/bl1) die "2017/2018" als "SeasonName" mit enthalten wäre?

**Comment by nilsology** [comment]
Zum Beispiel. Ich frage deshalb, da wenn ich die Daten importiere ja nicht direkt historisch zuordnen kann, in welcher Saison (2017/18) ein Spiel stattgefunden hat (außer manuell).

**Comment by christianTF** [comment]
Ich hänge mich hier an. Ich würde gerne die Tabelle der aktuellen Saison auslesen.

Es gibt den API-Call `https://www.openligadb.de/api/getbltable/bl1/2020` womit ich die Saison 2020/21 bekomme. Aber woher weiß mein Programm, wann ich 2020 und ab wann ich 2021 abfragen sollte?

Deswegen hätte ich versucht
`https://www.openligadb.de/api/getbltable/bl1`, also ohne Jahreszahl. Das liefert leider einen Fehler.

Ich würde gerne die Tabelle der aktuellen Saison auslesen.

lg, Christian

**Comment by Amminger** [comment]
Mir geht es ähnlich wie ChristanTF.
Es wäre wirklich hilfreich wenn man über <funktion>/bl1  immer die Daten der aktuellen Saison bekommen könnte. 
Für getmatchdata/bl1 funktioniert es ja schon. 

lg
Amminger

**Comment by msiggi** [comment]
https://[api.openligadb.de/getmatchdata/bl1](https://api.openligadb.de/getmatchdata/bl1)
