### ISSUE TITLE
Methoden Wünsche & Ideen

### ISSUE THREAD

**Issue by QuadStingray** [OpenLigaDB/OpenLigaDB-Samples#16]
Hallo Zusammen,

ich bin grade dabei mir eine Scala Version der API zu (https://github.com/QuadStingray/openligadb) schreiben. Dabei sind mir eine paar Methoden Ideen gekommen, die ich ganz cool fände. Ansonsten erstmal vielen Dank für die Arbeit!

* getTeamByID
* getMatchGroupByID
  => nur die Informationen
* GetMatchdataByGroupId
* Team.getNextMatch
  => über Ligen und Seasons hinweg
* Team.getLastMatch 
  => über Ligen und Seasons hinweg
* League.getCurrentSeason 
  https://github.com/OpenLigaDB/OpenLigaDB-Samples/issues/15 ist ein bisschen ähnlich, nur das ich eigentlich gerne von der Liga ausgehen würde.

**Comment by mayailkour** [comment]
Wie kann ich mir eigentlich das nächste Bundesligaspiel, das in Niedersachsen stattfindet, anzeigen lassen?
