### ISSUE TITLE
Endpoint für Tabellen?

### ISSUE THREAD

**Issue by nschloe** [OpenLigaDB/OpenLigaDB-Samples#17]
Gibt's einen API-Endpoint für die aktuelle Tabelle oder Saisonabschlusstabellen aus der Vergangenheit?

**Comment by msiggi** [comment]
Ja, gibt es. So z.B. für die 1. Bundesliga 2016/2017: https://www.openligadb.de/api/getbltable/bl1/2016

**Comment by nschloe** [comment]
Leider erst ab der Saison 2001/2002... :slightly_frowning_face:

**Comment by msiggi** [comment]
Ja, frühere Ligen müssten halt eingetragen werden. Das wäre natürlich eine Menge Arbeit....

**Comment by QuadStingray** [comment]
Gibt es auch die Möglichkeit das nach Spieltagen zu filtern?
Sprich: 2016 Spieltag 5 wer war an Platz X?

**Comment by Marc484** [comment]
Wann wird die Tabelle denn generiert?
