### ISSUE TITLE
Logos von Leipzig und Paderborn winzig

### ISSUE THREAD

**Issue by philpsc** [OpenLigaDB/OpenLigaDB-Samples#26]
Die Logos sind jeweils nur ein paar Pixel groß.

Bei Leipzig müsste die angeforderte Größe einfach angepasst werden: 
https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/800px-RB_Leipzig_2014_logo.svg.png

Als neue Quelle für Paderborn schlage ich vor:
https://upload.wikimedia.org/wikipedia/commons/e/e3/SC_Paderborn_07_Logo.svg

**Comment by msiggi** [comment]
Danke für die Hinweise, ist erledigt!
