### ISSUE TITLE
TeamIconUrl is wrong for Würzburger Kickers in bl3

### ISSUE THREAD

**Issue by mattsches** [OpenLigaDB/OpenLigaDB-Samples#27]
The `TeamIconUrl` for `bl3` team `<TeamName>FC Kickers Würzburg</TeamName>` is wrong, see [here](https://www.openligadb.de/api/getavailableteams/bl3/2019).

It should be one of the PNG files linked on [this Wikipedia Commons page](https://commons.wikimedia.org/wiki/File:W%C3%BCrzburger_Kickers_Logo.svg), I suppose (I'm not sure which size is preferred).

For example: [1024px](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/W%C3%BCrzburger_Kickers_Logo.svg/1024px-W%C3%BCrzburger_Kickers_Logo.svg.png)

**Comment by msiggi** [comment]
Thanks!
