### ISSUE TITLE
Berechnung/Erhöhung aktueller Spieltag

### ISSUE THREAD

**Issue by Outi77** [OpenLigaDB/OpenLigaDB-Samples#28]
Hallo,
laut Angabe in Github wechselt der aktuelle Spieltag genau zur Hälfte der Zeit zwischen dem letzten Spiel des letzten Spieltages und dem ersten Spiel des nächsten Spieltages. Ich habe das heute mal beobachtet, indem ich den Wert per Cronjob aller 5 Minuten abgefragt habe. Zum Zeitpunkt des Umswitchens (bzw. höchstens 5 Minuten danach) lies ich mir eine Message aufs Handy schicken. Diese kam 15:15 Uhr an. Ist das wirklich genau die Hälfte der Zeit zwischen dem Sonntag-Spiel (Union : RBL) und dem Freitag-Spiel (Köln : BVB)? Meiner Meinung nach hätte das Umswitchen entweder heute früh um 07:15 Uhr passieren müssen oder spätestens 08:07 Uhr (je nachdem ob hier der Zeitpunkt **vor** dem letzten Spiel oder **nach** dem letzten Spiel genommen wird). Eventuell könnte man das mal prüfen.

Grüße Outi

**Comment by Kristall-Rainer** [comment]
Hallo,

ich habe es zwar nicht aktiv überwacht, aber bei mir war heute Vormittag schon der neue Spieltag eingestellt. 

Viele Grüße 
Kristall-Rainer

**Comment by Outi77** [comment]
Hi,
also wie gesagt, der Cronjob lief seit 8 Uhr etwa und aller 5 Minuten diese api-Methode aufgerufen:
https://www.openligadb.de/api/getcurrentgroup/bl1

Ich berechne auf meiner Seite den Switch-Zeitpunkt selber und da war es irgendwann heute früh soweit.

Gruß zurück
Outi

**Comment by msiggi** [comment]
Hi Kristall-Rainer,

die Abfrage nach dem aktuellen Spieltag unterliegt intern einem Cache, um die ansonsten auftretende Vielzahl von Datenbank-Abfragen zu vermeiden. Es ist daher sehr wahrscheinlich, dass der Wechsel auf den aktuellen Spieltag nicht exakt in der zeitlichen Mitte zwischen den Spielen liegt.

Ist das ein Problem für Dich bzw. für Deine Applikation, wenn der Zeitpunkt nicht exakt der Mitte der Zeit zwischen dem letzen und dem nächsten Spieltag entspricht? Üblicherweise liegt da eine knappe Woche dazwischen, so dass es da evtl. nicht auf die Minute ankommt?

Grüße, Marcel

**Comment by Kristall-Rainer** [comment]
Hallo Marcel,

ich habe damit echt kein Problem. Auf die Minute oder sogar Stunde kommt es nicht an. Ich bin sehr zufrieden.

Viele Grüße 
_______________________
Matthias Lehmann

**Comment by Outi77** [comment]
Moin zusammen,
es stellt in der Tat kein Problem dar. Es ist mir nur aufgefallen und ich wollte nur mal nachfragen.
Alles gut, bin ebenfalls zufrieden...
