### ISSUE TITLE
Anzahl Requestes pro Tag

### ISSUE THREAD

**Issue by Outi77** [OpenLigaDB/OpenLigaDB-Samples#29]
Hallo zusammen,
ich wollte gern mal wissen, wieviele Requestes pro Tag nun eigentlich gestattet sind?
Unabhängig davon habe ich meine Abfrage mal dahin gehend umgebaut, dass ich nicht direkt eine Abfrage starte, sondern zuerst das _getlastchangedate_ checke. Allerdings komme ich mit minütlicher Abfrage trotzdem auf über 500 Requestst an einem Samstag. Ist das normal? Was sind Eure Erfahrungen damit?

Grüße Outi

**Comment by msiggi** [comment]
Hi Outi,

die Grenze der maximalen Abfragen pro Tag liegt derzeit bei 5.000 Requests pro Tag. Darunter fallen nicht die _getlastchangedate_-Methoden, diese haben keine Begrenzung. 

Die Requests werden der IP-Adresse zugeordnet. Eine Erklärung wäre, dass Deine Applikation auf einem Server liegt, wo auch andere die OpenLigaDB-Api nutzen. Ansonsten sollten 5.000 Abfragen für einen Samstag ausreichen.

Grüße, Marcel

**Comment by Outi77** [comment]
Hi Marcel,

also die Requests reichen locker. Wie gesagt, wir kommen an einem Samstag noch nicht mal auf 1000 Requests. Von daher alles gut ;)

Grüße Markus
