### ISSUE TITLE
/getmachtdata/bl1 nicht aktuell

### ISSUE THREAD

**Issue by philpsc** [OpenLigaDB/OpenLigaDB-Samples#34]
Hallo,

danke für die tolle kostenlose API.
Leider gibt /getmatchdata/bl1 aktuell den 21. Spieltag zurück. Richtig wäre der 26. Spieltag.

**Comment by Kristall-Rainer** [comment]
﻿Hallo,

gestern war der 21. Spieltag (Nachholspiel). Der 26. Spieltag ist morgen. Ich bin mir sicher, dass in den nächsten Stunden der 26. Spieltag angezeigt wird.
_______________________
Matthias

**Comment by philpsc** [comment]
Danke für den Hinweis, das Nachholspiel hatte ich nicht auf dem Schirm.
