### ISSUE TITLE
Group ID unterschiedlich

### ISSUE THREAD

**Issue by thomasmeyer57647** [OpenLigaDB/OpenLigaDB-Samples#35]
https://www.openligadb.de/api/getcurrentgroup/bl1 (Abgesetzt am 19.04.2020) ergibt:
`
`<Group xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api">
    <GroupID>34229</GroupID>
    <GroupName>30. Spieltag</GroupName>
    <GroupOrderID>30</GroupOrderID>
</Group>

mit der ID 34229

https://www.openligadb.de/api/getavailablegroups/bl1/2020 (Abgesetzt am 19.04.2020) ergibt:

<ArrayOfGroup xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/OLDB.Spa.Models.Api">
    <Group>
        <GroupID>35229</GroupID>
        <GroupName>1. Spieltag</GroupName>
        <GroupOrderID>1</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35230</GroupID>
        <GroupName>2. Spieltag</GroupName>
        <GroupOrderID>2</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35231</GroupID>
        <GroupName>3. Spieltag</GroupName>
        <GroupOrderID>3</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35232</GroupID>
        <GroupName>4. Spieltag</GroupName>
        <GroupOrderID>4</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35233</GroupID>
        <GroupName>5. Spieltag</GroupName>
        <GroupOrderID>5</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35234</GroupID>
        <GroupName>6. Spieltag</GroupName>
        <GroupOrderID>6</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35235</GroupID>
        <GroupName>7. Spieltag</GroupName>
        <GroupOrderID>7</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35236</GroupID>
        <GroupName>8. Spieltag</GroupName>
        <GroupOrderID>8</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35237</GroupID>
        <GroupName>9. Spieltag</GroupName>
        <GroupOrderID>9</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35238</GroupID>
        <GroupName>10. Spieltag</GroupName>
        <GroupOrderID>10</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35239</GroupID>
        <GroupName>11. Spieltag</GroupName>
        <GroupOrderID>11</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35240</GroupID>
        <GroupName>12. Spieltag</GroupName>
        <GroupOrderID>12</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35241</GroupID>
        <GroupName>13. Spieltag</GroupName>
        <GroupOrderID>13</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35242</GroupID>
        <GroupName>14. Spieltag</GroupName>
        <GroupOrderID>14</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35243</GroupID>
        <GroupName>15. Spieltag</GroupName>
        <GroupOrderID>15</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35244</GroupID>
        <GroupName>16. Spieltag</GroupName>
        <GroupOrderID>16</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35245</GroupID>
        <GroupName>17. Spieltag</GroupName>
        <GroupOrderID>17</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35246</GroupID>
        <GroupName>18. Spieltag</GroupName>
        <GroupOrderID>18</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35247</GroupID>
        <GroupName>19. Spieltag</GroupName>
        <GroupOrderID>19</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35248</GroupID>
        <GroupName>20. Spieltag</GroupName>
        <GroupOrderID>20</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35249</GroupID>
        <GroupName>21. Spieltag</GroupName>
        <GroupOrderID>21</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35250</GroupID>
        <GroupName>22. Spieltag</GroupName>
        <GroupOrderID>22</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35251</GroupID>
        <GroupName>23. Spieltag</GroupName>
        <GroupOrderID>23</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35252</GroupID>
        <GroupName>24. Spieltag</GroupName>
        <GroupOrderID>24</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35253</GroupID>
        <GroupName>25. Spieltag</GroupName>
        <GroupOrderID>25</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35254</GroupID>
        <GroupName>26. Spieltag</GroupName>
        <GroupOrderID>26</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35255</GroupID>
        <GroupName>27. Spieltag</GroupName>
        <GroupOrderID>27</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35256</GroupID>
        <GroupName>28. Spieltag</GroupName>
        <GroupOrderID>28</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35257</GroupID>
        <GroupName>29. Spieltag</GroupName>
        <GroupOrderID>29</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35258</GroupID>
        <GroupName>30. Spieltag</GroupName>
        <GroupOrderID>30</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35259</GroupID>
        <GroupName>31. Spieltag</GroupName>
        <GroupOrderID>31</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35260</GroupID>
        <GroupName>32. Spieltag</GroupName>
        <GroupOrderID>32</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35261</GroupID>
        <GroupName>33. Spieltag</GroupName>
        <GroupOrderID>33</GroupOrderID>
    </Group>
    <Group>
        <GroupID>35262</GroupID>
        <GroupName>34. Spieltag</GroupName>
        <GroupOrderID>34</GroupOrderID>
    </Group>
</ArrayOfGroup>

mit der ID 35258 für den 30. Spieltag

**Comment by Kristall-Rainer** [comment]
getavailablegroups/bl1/2019 sind die Spieltage der 1.Bundesliga der aktuellen Saison 2019/20. Die u.g. IDs der Spieltage sind dann die für die Saison 2020/21.

Viele Grüße
Kristall-Rainer
