### ISSUE TITLE
Neue Spieldaten (Anstoß-Zeiten) nach Zwangspause wegen Corona

### ISSUE THREAD

**Issue by Outi77** [OpenLigaDB/OpenLigaDB-Samples#36]
Hallo zusammen,
da es ja nun offensichtlich in absehbarer Zeit weiter geht mit dem Liga-Betrieb, wollte ich fragen, ob Hilfe beim Ändern der Matches benötigt wird? Würde dabei gern mithelfen, bräuchte dann allerdings auch die Berechtigung dafür...
Grüße aus NRW

**Comment by Kristall-Rainer** [comment]
Ich habe mir dafür heute schon Zeit eingeplant. Wenn sie die Spieltage so lassen (wovon ich ausgehe), dann geht es relativ fix.

Was natürlich nicht heißen soll, dass du dafür keine Rechte bekommen sollst ;-)

Grüße aus Berlin

**Comment by Outi77** [comment]
Wie ich es mitbekommen habe, wird mit dem 26. Spieltag weitergemacht.
OK...wie gesagt, falls Hilfe benötigt wird, sag' bescheid.
Gruß

**Comment by msiggi** [comment]
Hi Outi77,
ich habe Dir die entsprechenden Rechte erteilt. ;-)
