### ISSUE TITLE
API-Aufruf für den aktuellen Spieltag liefert nicht mehr die richtigen Paarungen

### ISSUE THREAD

**Issue by RealQuick4711** [OpenLigaDB/OpenLigaDB-Samples#37]
Ich nutze https://www.openligadb.de/api/getmatchdata/bl1 bzw. https://www.openligadb.de/api/getmatchdata/bl2 um auf einer Smartwatch Fussballergebnisse anzuzeigen. Bis vor wenigen Tagen hat das problemlos funktioniert. Jetzt wird für die 2. Liga der 26. Spieltag ausgegeben. Richtig wäre der 30. Spieltag.
Für die erste Liga wird der 24. Spieltag ausgewiesen.

Das ist deckungsgleich mit dem markierten Spieltag in der Auswahl auf der Seite https://www.openligadb.de/Spielplan/4362/1

**Comment by Kristall-Rainer** [comment]
Es liefen gestern Nachholespiele.
2.BL - 26. Spieltag H96SGD
1.BL - 24. Spieltag SCWSGE

Der zeitlich nächstgelegene Spieltag ist also der jeweils obengenannte. Heute Abend wird es dann auf den 30. Spieltag wechseln.

Viele Grüße 
_______________________
