### ISSUE TITLE
1.Bundesliga-Saison 2020

### ISSUE THREAD

**Issue by Outi77** [OpenLigaDB/OpenLigaDB-Samples#38]
Hallo zusammen,

ich habe gesehen, dass auf OpenLigaDB bereits die neuen Partien für die kommende Saison eingegeben wurden. Allerdings hat sich das Kürzel der Liga geändert. Bleibt das so (bl1_db) oder wird das noch umbenannt wie früher?
Bitte um Aufklärung!

Grüße Markus

**Comment by msiggi** [comment]
Hallo Markus,

danke für Deinen Hinweis. Die Liga mit der ID 4442 ist nun die offizielle 1. Fußball Bundesliga der Saison 2020/2021 mit dem Shortcut 'bl1'.

Grüße, Marcel

**Comment by Kristall-Rainer** [comment]
Hallo Marcel,

kannst du mir (Kristall-Rainer) wieder Admin-Rechte geben?

Vielen Dank

_______________________
Matthias Lehmann

**Comment by msiggi** [comment]
Ok, erledigt!
