### ISSUE TITLE
Alle Spiele eines Teams

### ISSUE THREAD

**Issue by kamami** [OpenLigaDB/OpenLigaDB-Samples#43]
Hallo,

gibt es eine Möglichkeit über diese API alle Spiele der Bundesligasaison abzurufen, bei denen bspw. 1. FC Köln teilnimmt?

Grüße

Martin

**Comment by KaterMikesch** [comment]
Hallo Martin,

ich wüsste nicht, dass es genau eine solche Abfrage gibt. Allerdings kann man alle Spiele der Saison abrufen und aus diesen die Spiele eines Vereins herausfiltern, so dass nur noch diese übrig bleiben.

Brauchst du dazu Hilfe? Falls ja, melde dich einfach. :-)

Gruß, Akki

**Comment by kamami** [comment]
Hallo Akki,

danke für die Antwort. Diese Option ist mir bewusst, allerdings würde ich nur ungern bei jedem HTTP Request immer alle Spiele der ganzen Saison auf einmal abrufen... Hatte gehofft, dass es mehr Query-Möglichkeiten gibt. Vorallem, weil man bereits explizit nach dem nächsten Spiel eines Teams filtern kann.

Beste Grüße

Martin

> Hallo Martin,
> 
> ich wüsste nicht, dass es genau eine solche Abfrage gibt. Allerdings kann man alle Spiele der Saison abrufen und aus diesen die Spiele eines Vereins herausfiltern, so dass nur noch diese übrig bleiben.
> 
> Brauchst du dazu Hilfe? Falls ja, melde dich einfach. :-)
> 
> Gruß, Akki

Hallo Akki,

danke für die Antwort. Diese Option ist mir bewusst, allerdings würde ich nur ungern bei jedem HTTP Request immer alle Spiele der ganzen Saison auf einmal abrufen... Hatte gehofft, dass es mehr Query-Möglichkeiten gibt. Vorallem, weil man bereits explizit nach dem nächsten Spiel eines Teams filtern kann.

Beste Grüße

Martin

**Comment by msiggi** [comment]
Hallo Martin,

versuch mal https://api.openligadb.de/getmatchdata/bl1/2020/K%C3%B6ln

Ist es das, was Du meinst?

Grüße, Marcel

**Comment by Outi77** [comment]
Krass, das wußte ich bisher auch noch nicht. Coole Sache ;)
