### ISSUE TITLE
Heimspiel

### ISSUE THREAD

**Issue by Portagoras** [OpenLigaDB/OpenLigaDB-Samples#45]
Ich habe mich mal etwas umgesehen, konnte aber keine Infos dazu finden.

Für mich wäre es interessant zu sehen, ob ein Spiel ein Heimspiel ist, (oder ein Auswärtsspiel, aber das ergibt sich ja).

Gibt es eine Möglichkeit die TeamIds mit den zugehörigen LocationIds abzufragen?

**Comment by GoestaHuppenbauer** [comment]
wenn ich das richtige sehe wird das Stadion ja mit angegeben. Über ein Array welches Stadion zu welchem Team gehört könnte ermittelt werden ob heim oder auswärts

**Comment by Outi77** [comment]
Also eigentlich ist aus _getmatchdata_ das Team mit ['Team**1**']['TeamId'] das **Heimteam** und das Team mit ['Team**2**']['TeamId'] das **Auswärtsteam**.

**Comment by msiggi** [comment]
siehe https://github.com/OpenLigaDB/OpenLigaDB-Samples/issues/45#issuecomment-848550459
