### ISSUE TITLE
TopScorers multiple times

### ISSUE THREAD

**Issue by GoestaHuppenbauer** [OpenLigaDB/OpenLigaDB-Samples#46]
In the top scorer List Players show up multiple times with different tipes of Writing Methods of the name. 

. Robert, Lewandowski 
. Lewandowski

**Comment by Outi77** [comment]
Hey,

look at this thread [https://github.com/OpenLigaDB/OpenLigaDB-Samples/issues/33](url)

**Comment by msiggi** [comment]
duplicated issue #33
