### ISSUE TITLE
REST API äquivalent zu GetAvailLeagues / GetAvailSports?

### ISSUE THREAD

**Issue by tofi92** [OpenLigaDB/OpenLigaDB-Samples#47]
Moin, gibt's in der REST API schon ein Äquivalent zu den oben genannten Funktionen?

**Comment by msiggi** [comment]
Hi,

meinst Du diese Methoden?

https://api.openligadb.de/getavailablesports
https://api.openligadb.de/getavailableleagues

**Comment by tofi92** [comment]
Wow, sehr spätes Reply, aber da war ich wohl blind :) Danke!
