### ISSUE TITLE
Probleme mit Borussia Dortmund Daten

### ISSUE THREAD

**Issue by misxka** [OpenLigaDB/OpenLigaDB-Samples#49]
Hallo.
Es gibt eine Probleme mit der Daten, die Borussia Dortmund beschreiben. z.B. es gibt kein Team-Logo Url, ShortName, TeamName. Diese Situation in einem Response ist unten dargestellt.
![issue](https://user-images.githubusercontent.com/57208499/126982472-76327626-41d8-4dce-8cf8-59c87df4c1d2.PNG)
Danke im Voraus.

**Comment by Reo1980** [comment]
Kann ich bestätigen. Da sind wohl die Daten des Vereins gelöscht worden.

**Comment by misxka** [comment]
Danke. So wie ich sehe, diese Probleme ist gelöst.
