### ISSUE TITLE
Logo Union Berlin

### ISSUE THREAD

**Issue by plueschpruem** [OpenLigaDB/OpenLigaDB-Samples#52]
Ggfs. kommt es ja überraschend, dass deren Verein derzeit auf Platz 1 der 1. Liga steht, das Logo gibt es allerdings – so wie die anderen – auch in schön / als SVG:
https://de.wikipedia.org/wiki/1._FC_Union_Berlin#/media/Datei:1._FC_Union_Berlin_Logo.svg

**Comment by msiggi** [comment]
Aus nicht näher untersuchten Gründen funktioniert der Link nicht, wenn das Logo in die Website eingebunden ist.
