### ISSUE TITLE
Spiele für einen Ort abfragen (unabhängig von der Liga)

### ISSUE THREAD

**Issue by eilissadh** [OpenLigaDB/OpenLigaDB-Samples#53]
Ist eine Abfrage von allen Spielen an einem Ort möglich?
Ich würde z.B. gerne wissen, welche Spiele in München stattfinden, egal ob 1. Bundesliga, 2. Bundesliga, DFB Pokal, UEFA Champions Legaue, WM, etc.. 
Vielen Dank!

**Comment by nkl-kst** [comment]
> Ist eine Abfrage von allen Spielen an einem Ort möglich? Ich würde z.B. gerne wissen, welche Spiele in München stattfinden, egal ob 1. Bundesliga, 2. Bundesliga, DFB Pokal, UEFA Champions Legaue, WM, etc.. Vielen Dank!

Bin nur beim Stöbern auf diese API und dein Issue gestoßen, daher kann ich deine Frage leider nicht beantworten (würde aber vermuten, dass diese Informationen so aktuell nicht abrufbar sind). Falls dir eine interaktive Karte ausreicht, könntest du mal auf www.soccer-map.com vorbeischauen, da wirst du bestimmt fündig :)
