### ISSUE TITLE
Spielplan eines Teams

### ISSUE THREAD

**Issue by webquartier** [OpenLigaDB/OpenLigaDB-Samples#59]
Der **Spielplan eines Team** (ID 40) endet im Jahr 2016, z.B. der des FC Bayern München, auch, wenn es danach noch Spiele und Ergebnisse in verschiedenen Ligen gibt. Wie kann man auch **spätere Ergebnisse für einen historischen Spielplan** abfragen?

Beispiel: https://api.openligadb.de/getmatchesbyteamid/40/1500/0

Sinnvoll wäre die Zeit als Parameter (Start- und Endzeit statt Wochen davor und danach) zu übergeben, damit nicht zu viele Spiele gleichzeitig geladen werden müssen.

**Comment by webquartier** [comment]
Der Spielplan eines Teams liefert keine Ergebnisse, z.B. die Team-ID 1991 aus der Regionalliga Nordost (ID: 4623).

Beispiel: https://api.openligadb.de/getmatchesbyteamid/1991/0/100

**Comment by msiggi** [comment]
solved!
