### ISSUE TITLE
Failed to read OpenligaDB Bl1 programmatically

### ISSUE THREAD

**Issue by d002902** [OpenLigaDB/OpenLigaDB-Samples#65]
The Browser  delivers the expected data:
https://api.openligadb.de/getmatchdata/bl1/2023    
https://api.openligadb.de/getavailableteams/bl1/2023 

but not programmatically.
Are there changes necessary? (Last 2022/2023 worked fine.)
Please advise.

Thanks and regards Michael

**Comment by KaterMikesch** [comment]
Same here.

**Comment by meyomey** [comment]
also here for bl1.
bl2 is working.

**Comment by msiggi** [comment]
Please, check the upper and lower case of the objects. Yes, for several reasons we had to change this spelling

For example, the date of the match is now "matchDateTime", former "MatchDateTime".

I´m very sorry, if you have trouble with this...

**Comment by d002902** [comment]
Thanks. But the issue – to be more precise – is:

If I run Chrome with https://api.openligadb.de/getavailableteams/bl1/2023 - I got the expected data (teams of season 2023/2024)

If I run my program (Vb.net) I got nothing.

Even worse:

Chrome with https://api.openligadb.de/getmatchdata/bl1/2023  I get expected data (all games of season 2023/2024)

If I run my program (Vb.net) I got Spieltag34 results last season (2022/2023).

Regards

Michael

 

 

 

Von: Marcel Siegel ***@***.***> 
Gesendet: Montag, 3. Juli 2023 10:08
An: OpenLigaDB/OpenLigaDB-Samples ***@***.***>
Cc: d002902 ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenLigaDB/OpenLigaDB-Samples] Failed to read OpenligaDB Bl1 programmatically (Issue #65)

 

Please, check the upper and lower case of the objects. Yes, for several reasons we had to change this spelling

For example, the date of the match is now "matchDateTime", former "MatchDateTime".

I´m very sorry, if you have trouble with this...

**Comment by meyomey** [comment]
In my application the query of teams and matchdays for *bl2* (2023/2024)
was ok.

For *bl1* (2023/2024) the teams are displayed correctly, but for all 34
matchdays the date 1.01.1970 01:00 is always displayed.

In "Datenhaushalt" there is a second *bl* entry:

1. Fussball Bundesliega 2024 bl1 4622 0 0 boother 25.03.2023

Can it possibly also be related to this?

Am Mo., 3. Juli 2023 um 12:28 Uhr schrieb d002902 ***@***.***

**Comment by d002902** [comment]
Hi,

meanwhile we detected that in case of bl1 (season 2023/2024)  the Url in the call is truncated: the year disappears – in  your  OpenLigaDB environment, 

but NOT for bl2. That’s why bl2 works for Spielplan for the new season.

Double check this issue again, thanks. 

Michael

 

 

 

 

 

Von: Marcel Siegel ***@***.***> 
Gesendet: Montag, 3. Juli 2023 10:08
An: OpenLigaDB/OpenLigaDB-Samples ***@***.***>
Cc: d002902 ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenLigaDB/OpenLigaDB-Samples] Failed to read OpenligaDB Bl1 programmatically (Issue #65)

 

Please, check the upper and lower case of the objects. Yes, for several reasons we had to change this spelling

For example, the date of the match is now "matchDateTime", former "MatchDateTime".

I´m very sorry, if you have trouble with this...

**Comment by msiggi** [comment]
@d002902, @meyomey : Sorry, but I can not reproduce any of your issues. It seems, the problem is related to your clients, because:

1. As you mentioned, in browser all values where returned correct.
2. I added [angular-with-Results-complete-league.html](https://github.com/OpenLigaDB/OpenLigaDB-Samples/blob/master/angularjs/angular-with-Results-complete-league.html), please try it as a minimal api-client. In my environment all matches returned as expected. Please take a look in the code, is my request maybe partly different from yours?

**Comment by d002902** [comment]
Thanks! Meanwhile most of the api’s for the new season are working now as expected!

 

 

Von: Marcel Siegel ***@***.***> 
Gesendet: Montag, 3. Juli 2023 20:18
An: OpenLigaDB/OpenLigaDB-Samples ***@***.***>
Cc: d002902 ***@***.***>; Mention ***@***.***>
Betreff: Re: [OpenLigaDB/OpenLigaDB-Samples] Failed to read OpenligaDB Bl1 programmatically (Issue #65)

 

@d002902 <https://github.com/d002902> , @meyomey <https://github.com/meyomey>  : Sorry, but I can not reproduce any of your issues. It seems, the problem is related to your clients, because:

1.	As you mentioned, in browser all values where returned correct.
2.	I added angular-with-Results-complete-league.html <https://github.com/OpenLigaDB/OpenLigaDB-Samples/blob/master/angularjs/angular-with-Results-complete-league.html> , please try it as a minimal api-client. In my environment all matches returned as expected. Please take a look in the code, is my request maybe partly different from yours?

**Comment by KaterMikesch** [comment]
Works for me with the new Base-URL. Thanks. The breaking change (lower-upper-case) happened a while ago in the midst of the season. I already changed that.

All in all much better now with the Swagger based API. The transition was not really 100% smooth but it is a really, really nice project anyway. Thanks a ton.

**Comment by msiggi** [comment]
> The transition was not really 100% smooth

I know about, sorry again.

> but it is a really, really nice project anyway. Thanks a ton.

Thank you ;-)
