### ISSUE TITLE
Soap service changed?

### ISSUE THREAD

**Issue by meyomey** [OpenLigaDB/OpenLigaDB-Samples#66]
I have taken over an old installation of a football prediction game. 
There the soap service https://api.openligadb.de/webservices/sportsdata.asmx is still used. 
The teams, all games could be read in via it, also the results of the first matchday of the 2nd league appeared. 
For the second match day the results were missing. 
Has something been changed here?

**Comment by msiggi** [comment]
Hi, 

what method you are calling? Do you mean _GetMatchdataByGroupLeagueSaison_ with parameters 1,'bl2','2023' is working properly and using 2,'bl2','2023' is not working?

I cannot reproduce it!

**Comment by meyomey** [comment]
Yes, i mean GetMatchdataByGroupLeagueSaison. 
On the first match day it worked without problems, on the second no results were delivered from Friday to Sunday. I tested it again in the middle of the week. Then all final and half-time results were delivered again, except for the half-time result of the Hertha - Wiesbaden match. 

![Tippcup Bundesliga ](https://github.com/OpenLigaDB/OpenLigaDB-Samples/assets/33765557/9774de1e-547e-4726-b500-ce4ef5e94dea)

**Comment by msiggi** [comment]
sorry, too long ago. Please, reopen if issue is still relevant!
