### ISSUE TITLE
Teamvergleich-Problem (Männer/Frauen)

### ISSUE THREAD

**Issue by KaterMikesch** [OpenLigaDB/OpenLigaDB-Samples#67]
Beim Nutzen von Teamvergleichen getmatchdata/<team-a-id>/<team-b-id> tritt ein Problem auf:

Bei der 1. Bundesliga Frauen "bl1f" werden die gleichen Teams (Team-Ids) benutzt wie für die Männerteams bei der 1. Bundesliga "1bl". 

Das führt natürlich zu Ergebnissen, die nicht passen, weil dann gemischt wird.

Einen Lösungsvorschlag habe ich dafür allerdings noch nicht.

Blöde Geschichte.

**Comment by msiggi** [comment]
Wäre die Lösung eine separate Sportart "Frauenfußball"?

**Comment by KaterMikesch** [comment]
Wenn dadurch verhindert wird, dass Teams mit der gleichen Id wie bei den Männern verwendet werden kann, könnte das helfen. Bei "bl1f" kommt da aber dann jede Hilfe zu spät, oder? 🫣

Apropos "bl1f". Die Liga scheint nicht weiter gepflegt zu werden. Kannst du mir da Zugriff geben, damit ich die nächsten Spieltage eintragen kann?

**Comment by KaterMikesch** [comment]
> Wenn dadurch verhindert wird, dass Teams mit der gleichen Id wie bei den Männern verwendet werden kann, könnte das helfen. Bei "bl1f" kommt da aber dann jede Hilfe zu spät, oder? 🫣
> 
> Apropos "bl1f". Die Liga scheint nicht weiter gepflegt zu werden. Kannst du mir da Zugriff geben, damit ich die nächsten Spieltage eintragen kann?

Also für "Akki".

**Comment by msiggi** [comment]
Hallo @KaterMikesch,

ich habe eine neue Sportart "Frauenfußball" angelegt und die [Frauen WM](https://www.openligadb.de/Leagues/Manage?id=4640) sowie die [1. Frauen Fußball Bundesliga](https://www.openligadb.de/Leagues/Manage?id=4650) mit komplett eigenständigen Teams dorthin verschoben. Ebenso hast Du nun die Rechte für die Frauen Bundesliga.

Passt das so?

**Comment by KaterMikesch** [comment]
Danke, Marcel!

Sieht auf den ersten Blick gut aus. Ich schaue am Wochenende, wie es in der Praxis ist. Super, dass du so schnell eine Lösung finden konntest.
