### ISSUE TITLE
Laufender Spieltag

### ISSUE THREAD

**Issue by smiley561** [OpenLigaDB/OpenLigaDB-Samples#71]
"getcurrentgroup/bl1" gibt den 13. Spieltag aus obwohl wir schon den 18. hinter uns haben. Ebenso werden bei "getmatchdata/bl1" die Spiele vom 13. Spieltag ausgegeben.

**Comment by msiggi** [comment]
Das liegt an dem Nachholespiel von gestern Bayern gegen Union Berlin, welches erst gestern stattfand, jedoch dem 13. Spieltag zugeordnet ist. Spätestens morgen wird dann der 19. Spieltag ausgegeben.

**Comment by Kristall-Rainer** [comment]
Gestern war Nachholespiel vom 13. Spieltag: Bayern gegen Union._______________________Matthias LehmannAm 25.01.2024 um 13:45 schrieb Marcel Siegel ***@***.***>:﻿
Das liegt an dem Nachholespiel von gestern Bayern gegen Union Berlin, welches erst gestern stattfand, jedoch dem 13. Spieltag zugeordnet ist. Spätestens morgen wird dann der 19. Spieltag ausgegeben.
