### ISSUE TITLE
Team Groups (Tournament Mode)

### ISSUE THREAD

**Issue by sdsJobe** [OpenLigaDB/OpenLigaDB-Samples#8]
When creating a tournament, it would be usefull to have the ability to declare groups for the teams. To set points and stats for the team.

Es wäre schön eine Gruppenfunktion bei Turnieren zu haben, um die Mannschaften in Gruppen zu verschieben und dort eine Punktevergabe zu realisieren.

**Comment by BVBen** [comment]
Ich könnte dieses Feature gerade auch gut gebrauchen hinsichtlich der WM. Alle Teams kann man ja abrufen, allerdings fehlt eine Zuordnung zu den Gruppen.

**Comment by sdsJobe** [comment]
Ja leider nach wie vor.


BVBen <notifications@github.com> schrieb am Mo. 14. Mai 2018 um 17:45:

**Comment by msiggi** [comment]
Hier ein Anfang:
https://plus.google.com/u/0/b/105834637802799309125/105834637802799309125/posts/QGQmn5ZkBj6

**Comment by gluehloch** [comment]
> Hier ein Anfang:
> https://plus.google.com/u/0/b/105834637802799309125/105834637802799309125/posts/QGQmn5ZkBj6

Auf das Dokument kann man als Privatanwender nicht mehr zugreifen.
