### ISSUE TITLE
Feature request: Sub-Topics in MQTT

### ISSUE THREAD

**Issue by hokascha** [OpenLigaDB/OpenLigaDB-Samples#81]
Im Moment werden alle Änderungen im Topic `openligadb` veröffentlicht. 

Es wäre wünschenswert, stattdessen das Topic `openligadb/<leagueShortcut>` zu verwenden, also z.B. `openligadb/bl1`. 

Damit wäre es möglich, einzelne Ligen zu beobachten und so z.B. nur die primären, gut gepflegten Ligen zu abonnieren.
Gleichzeitig wäre es durch Verwendung von Wildcards weiterhin möglich, alle Ligen zu abonnieren: `openligadb/#`

**Comment by xdream77** [comment]
Wenn du einen Javascript Server hast, genau für diesen Fall habe ich ein package geschrieben, welches allerdings noch in der Beta Phase ist.

[Schau doch mal rein](https://jsr.io/@wgd/oldb)

**Comment by hokascha** [comment]
Ich bin leider nicht auf Node oder dergleichen. Es wäre aber tatsächlich viel einfacher, wenn OLDB direkt die Sub-Topics nutzen würde ;-)

**Comment by msiggi** [comment]
Ok, done. Siehe [hier](https://github.com/OpenLigaDB/OpenLigaDB-Samples/discussions/77#discussion-6763232) die aktualisierte Beschreibung!

**Comment by hokascha** [comment]
Sehr cool, danke!
