### ISSUE TITLE
AvailableLeagues haben keine Sport ID

### ISSUE THREAD

**Issue by slindenberg** [OpenLigaDB/OpenLigaDB-Samples#86]
Moin, ich würde in meiner App gerne zuerst die Sportart und dann die Liga auswählbar machen.

Wenn ich "/getavailableleagues" aufrufe, ist das Element "Sport" immer "null". Daher fehlt mir die Referenz auf den jew. Sport. Könnt ihr das bitte noch hinzufügen? Sport.id würde reichen.

Vielen Dank!

**Comment by msiggi** [comment]
Danke für den Hinweis! Nun sollte das Objekt vollständig sein.

**Comment by slindenberg** [comment]
Super und so schell, vielen Dank!
