### ISSUE TITLE
Regression bei "em" getmatchdata

### ISSUE THREAD

**Issue by KaterMikesch** [OpenLigaDB/OpenLigaDB-Samples#87]
Es gibt seit Kurzem folgendes, vermutlich nicht beabsichtigtes Verhalten:

https://api.openligadb.de/getmatchdata/em/2024/7

liefert derzeit nur `[]`

https://api.openligadb.de/getmatchdata/em/2024/

hingegen richtige Daten für alle Spiele.

Das war vor Kurzem bereits schon einmal so und funktionierte dann wieder. Wird daran gerade gearbeitet?

Schöner Gruß aus Köln!

**Comment by KaterMikesch** [comment]
<img width="785" alt="Bildschirmfoto 2024-07-11 um 17 04 35" src="https://github.com/OpenLigaDB/OpenLigaDB-Samples/assets/229389/26afa639-e508-4aca-8e0a-8349cf72f1c4">

Fupptipp sieht daher gerade leider so aus.

**Comment by msiggi** [comment]
sorry, es war ein temporäres Problem!

**Comment by KaterMikesch** [comment]
Danke, Marcel!
