### ISSUE TITLE
Torschützen werden nicht gespeichert

### ISSUE THREAD

**Issue by Reo1980** [OpenLigaDB/OpenLigaDB-Samples#9]
Wenn ich in der Ligaverwaltung (Beispiel https://www.openligadb.de/Ergebnisse/4154/1) einen Torschützen eintrage, dann wird dieser nicht gespeichert.
Macht ich etwas falsch oder hat sich hier ein Bug eingeschlichen?

**Comment by msiggi** [comment]
Danke für den Hinweis - läuft wieder! Ggf. muss der Browser-Cache geleert werden!
